function executarOperacao(){
    try {
        throw new Error("Erro Gen√©rico")
    } catch (erro){
        console.log("Erro: ", (erro as Error).message);
    }
}

executarOperacao();